data:
  train:
    - data/differential/preprocessed/train
  validation:
    - data/differential/preprocessed/validation
  test:
    - data/differential/preprocessed/test
trainer:
  inputs:
    - name: gradient
      dim: 1
  support_inputs:
    - nodal_grad_x_5
    - nodal_grad_y_5
    - nodal_grad_z_5
  outputs:
    - name: laplacian
      dim: 1
  prune: true
  batch_size: 5
  n_epoch: 1000
  log_trigger_epoch: 1
  stop_trigger_epoch: 10
  seed: 0
  lazy: true
  num_workers: 0
model:
  blocks:
    - name: IN_LINEAR
      type: adjustable_mlp
      bias: false
      destinations:
        - MUL
      nodes:
        - -1
        - 64
      activations:
        - identity
    - name: ISO_GCN_CONTRACTION
      type: iso_gcn
      is_first: true
      destinations:
        - MLP
      support_input_indices:
        - 0
        - 1
        - 2
      nodes:
        - -1
        - 64
      activations:
        - identity
      optional:
        ah_w: true
        propagations:
          - contraction
        factor: 5.213283280931938
    - name: MLP
      type: adjustable_mlp
      destinations:
        - MUL
      nodes:
        - -1
        - 64
        - 64
        - 64
      activations:
        - tanh
        - tanh
        - identity
    - name: MUL
      type: reducer
      destinations:
        - ISO_GCN
      optional:
        operator: mul
    - name: ISO_GCN
      type: iso_gcn
      bias: false
      destinations:
        - OUT_MLP
      support_input_indices:
        - 0
        - 1
        - 2
      nodes:
        - -1
        - 64
      activations:
        - identity
      optional:
        ah_w: true
        propagations:
          - contraction
        factor: 5.213283280931938
    - name: OUT_MLP
      type: mlp
      bias: false
      nodes:
        - -1
        - 64
        - 8
        - -1
      activations:
        - tanh
        - tanh
        - identity
