data:
  train:
    - data/differential/preprocessed/train
  validation:
    - data/differential/preprocessed/validation
  test:
    - data/differential/preprocessed/test
trainer:
  inputs:
    - name: gradient
      dim: 1
  support_inputs:
    - nodal_nadj
  outputs:
    - name: hessian
      dim: 1
  prune: true
  batch_size: 5
  n_epoch: 1000
  log_trigger_epoch: 1
  stop_trigger_epoch: 10
  seed: 0
  lazy: true
  num_workers: 0
model:
  blocks:
    - name: RESHAPE
      type: reshape
      destinations:
        - IN_LINEAR
      optional:
        new_shape:
          - -1
          - 3
    - name: IN_LINEAR
      type: adjustable_mlp
      bias: false
      destinations:
        - MUL
        - GCNII_CONTRACTION
      nodes:
        - -1
        - 64
      activations:
        - identity
    - name: GCNII_CONTRACTION
      type: gcnii
      destinations:
        - MLP
      nodes:
        - -1
        - 64
        - 64
      activations:
        - tanh
        - identity
      optional:
        ah_w: true
    - name: MLP
      type: adjustable_mlp
      destinations:
        - MUL
      nodes:
        - -1
        - 64
      activations:
        - identity
    - name: MUL
      type: reducer
      destinations:
        - GCNII
      optional:
        operator: mul
    - name: GCNII
      type: gcnii
      bias: false
      destinations:
        - OUT_LINEAR
      nodes:
        - -1
        - 64
        - 64
      activations:
        - tanh
        - identity
      optional:
        ah_w: true
    - name: OUT_LINEAR
      type: mlp
      destinations:
        - ARRAY2SYMMAT
      bias: false
      nodes:
        - -1
        - 6
      activations:
        - identity
    - name: ARRAY2SYMMAT
      type: array2symmat
